[project]
name = "nfl2026"
version = "0.9.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.6.0",
    "torch-geometric>=2.7.0",
    "pyg-lib==0.5.0+pt26cu124",
    "torch-cluster==1.6.3+pt26cu124",
    "torch-scatter==2.1.2+pt26cu124",
    "torch-sparse==0.6.18+pt26cu124",
    "torch-spline-conv==1.2.2+pt26cu124",
    "jaxtyping>=0.3.3",
    "einops>=0.8.1",
    "lightning==2.5.5",
]

[tool.uv.sources]
torch = { index = "torch_cu124" }

[[tool.uv.index]]
name = "torch_cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv]
find-links = [
    "https://data.pyg.org/whl/torch-2.6.0+cu124.html",
]

[tool.hatch.build.targets.wheel]
packages = ["nfl2026"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

